version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/vsgg
    overwrite: yes
permissions:
  - object: /home/ubuntu/vsgg
    owner: root
    group: root
    mode: 755
hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 500
      runas: ubuntu